### PR TITLE
lpips v0.1.4

### PR DESCRIPTION
**Pull request by jeongseok-meta**
The second attempt at resolving remaining issues in https://github.com/conda-forge/lpips-feedstock/pull/2

Resolves https://github.com/conda-forge/lpips-feedstock/pull/2

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by jeongseok-meta** [comment]
@conda-forge-admin, please rerender

**Comment by jeongseok-meta** [comment]
@conda-forge/core, please review this PR. Unfortunately, this feedstock hasn't had any activity from its maintainers since it was created: https://github.com/conda-forge/lpips-feedstock/commits/main/

**Comment by jeongseok-meta** [comment]
@conda-forge-admin, please rerender

**Comment by ocefpaf** [comment]
> @conda-forge/core, please review this PR. Unfortunately, this feedstock hasn't had any activity from its maintainers since it was created: https://github.com/conda-forge/lpips-feedstock/commits/main/

Out policy is to wait for 1 week for the maintainers to respond. If they don't, please ping us again.

**Comment by wolfv** [comment]
@ocefpaf I agree with this in general, but this particular group of maintainers has unfortunately been MIA for a while.

**Comment by wolfv** [comment]
@jeongseok-meta would you be OK with adding yourself as a maintainer?

**Comment by jeongseok-meta** [comment]
> @jeongseok-meta would you be OK with adding yourself as a maintainer?

Done! Thanks for taking this as an exception case!

https://github.com/conda-forge/lpips-feedstock/pull/5

**Pull request merged**
